# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  containerRegistryServiceConnection: 'containerRegistryServiceConnection'
  imageRepository: 'signedrepo'
  containerRegistry: 'signedimgcon.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/app/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
pool: MyAgentPool

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      inputs:
        command: login
        containerRegistry: $(containerRegistryServiceConnection)

    - task: DownloadSecureFile@1
      name: privateKey
      inputs:
        secureFile: new-key-1.key
    - script: |
        mkdir -p $(DOCKER_CONFIG)/trust/private
        cp $(privateKey.secureFilePath) $(DOCKER_CONFIG)/trust/private

    - task: Docker@2
      inputs:
        command: build
        dockerfile: $(dockerfilePath)
        containerRegistry: $(containerRegistryServiceConnection)
        repository: $(imageRepository)
        tags: |
          $(tag)
        arguments: '--disable-content-trust=false'

    - task: AzureCLI@2
      displayName: Content Trust Sign and Push
      inputs:
        azureSubscription: 'RmServiceConnection'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az acr login -n $(containerRegistry)
          echo $(DOCKER_CONFIG)/trust/private/new-key-1.key | base64 --decode > $(DOCKER_CONFIG)/trust/private/delegate.key
          chmod 400 $(DOCKER_CONFIG)/trust/private/delegate.key
          export DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE=$(DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE)
          docker trust key load $(DOCKER_CONFIG)/trust/private/new-key-1.key --name delegationkey 
          export DOCKER_CONTENT_TRUST=1
          docker trust sign $(containerRegistry)/$(imageRepository):$(tag)
          docker trust inspect --pretty $(containerRegistry)/$(imageRepository):$(tag)

    # - task: Docker@2
    #   inputs: 
    #     command: push
    #     containerRegistry: $(containerRegistryServiceConnection)
    #     repository: $(imageRepository)
    #     tags: |
    #       $(tag)
    #     arguments: '--disable-content-trust=false'
    #   env:
    #     DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: $(DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE)

